### ISSUE TITLE
Certificate Based Client VPN Endpoint needs OVPN files updated with Cert and Key

### ISSUE THREAD

**Issue by bmisesf** [sourcefuse/terraform-aws-arc-vpn#11]
We need an additional automation (included in Terraform module) for client VPN with Authentication type: "certificate-authentication".

Currently, when OVPN file is generated/downloaded, it is missing Certificate (cert tag) and the Key (key tag).

Certificate and the Key are already stored in this module in Parameter Store.

E.g.
self-signed-cert-ca.key
and
self-signed-cert-ca.pem

Instead of manually including those in downloaded file, a file with tags included should be generated in Terraform process, and stored in a S3 bucket.

**Comment by vijay-stephen** [comment]
@bmisesf Currently its not possible as Terraform doesn't support exporting config file
